### ISSUE TITLE
[Feature Request] Regularly execute user-defined actions when getting data in SPOT folders

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/spot2_container#2]
So, I'm in UUR-land for some of my SPOT uses, which opens up some possibilities. Namely, I can have a git repo on GitHub that all of my Jenkins jobs push my `.cali` profiles to. If the spot container could get a cron job to check out those repos, that would lead to a really slick workflow where I tell the SPOT hosting at NERSC to check out public profiles, and push my UUR profiles to those repos. Obviously, being me, I'm envisioning this shiny future where all the people who use ExaMiniMD (or LAMMPS) push their profiles to one of those repos, but that comes later.

I don't want to be too dogmatic about implementation, the first thing that came to my head would be that the spot container might take in a set of repos to clone (recursively) on container launch, and pull (recursively) with a cron job, but any path to "regularly pulling profiles from a set of public repos" would solve my problem.

**Comment by mplegendre** [comment]
Would the cron job need to be in the container?  Since the .cali files are mounted from outside the container, you could do the cron or any update on the host.

Or do you want the git update to happen on a browser's first access?  If so, that's probably not a cron job but a script hook.  We could add something like a "on a getData call, if $LOCATION/hook.py exists, then run it".  That'd be near trivial to add to spot.py, just a couple lines.  Feel free to submit a PR.

I do want to find a better .cali file management for the container.  With lorenz in LLNL it works really smoothly, being able to just browse the HPC file systems.  But I'm not a fan of mounting a directory that must be accessible to the web server.  That's really awkward if you run the server on your laptop.  

One idea was to shift to the database storage as the primary backing behind the container.  Users would have a script for submitting .cali files to the DB and SPOT would pull from it.  Most of the major the features are in place for that, but it's not well enough tested that we're including it in the release.

**Comment by DavidPoliakoff** [comment]
Browser's first access is honestly probably even better. Let me take a look at what implementing that would look like, good catch

**Comment by mplegendre** [comment]
BTW, a git history edit had to go into SPOTBE relatively recently.  If you have an old checkout, you may want to delete it and re-clone before creating any commits.

**Comment by DavidPoliakoff** [comment]
A bit more detail on why I said cron job: if the answer is "do those git pulls on the host" I need to figure out how to make that happen on NERSC, and LLNL, and my laptop, and and and....

If it's a part of the container, I solve it in the container and call it a day. That said, doing it on getData is the better approach for a number of reasons (especially the laptop case)

**Comment by DavidPoliakoff** [comment]
Ah, will do, on the git history thing (somehow I missed your comment). Could I talk you into one of these designs?

1) (preferred) There's a hook.py that gets called on `getData`. By default, this `hook.py` git pulls from a set of repos specified in `backend_config.yaml`. On container launch, those repos get `git cloned`. That said, people can freely add to hook.py to enable any other behavior they want to see happen on getData.
2) (less intrusive, perhaps) there's a hook.py located somewhere. On container creation, we run `python hook.py --this-is-the-time-this-script-is-being-run-on-initialization`. On getData(), we run `python hook.py --this-is-just-the-hook-from-a-getdata-invocation [url_args]`

**Comment by mplegendre** [comment]
My thought had been that the default hook.py would be empty/non-existent, and there doesn't need to be any SPOT infrastructure that assumes git.  The user could provide that when they write a hook.py.  That way other users could use this to get data from non-GIT sources too.

The hook lives in the top-level directory next-to/above your .cali files.  So when you setup your data source for the first time you provide the hook.py in that directory.  And that hook.py contains the git commands and URL that checkout/update the .cali files.  Then if someone else want's a hook.py to do a scp (for example), they could provide write that too.

And hook.py is a placeholder name.  Should actually be something like SPOTHookOnLoad.py, to both namespace and provide room for future hooks.

I could throw up a branch to demo what I'm thinking, if this is unclear.  As I said, I think it's just a couple lines.

**Comment by DavidPoliakoff** [comment]
If you're game to put up a demo branch, I'd appreciate it. I think I get what you're after, here, but you certainly are. What you've described meets my needs, so if you implement it in a way you're happy with, I'll use it.

**Comment by DavidPoliakoff** [comment]
Actually, a side benefit of your concept is that my repo that hosts my .cali files, can also host my [SomeHookName].py

**Comment by mplegendre** [comment]
(I know we're moving on from cron, but just a few other thoughts there for completeness)

I think cron in the container would be too unreliable in the end.  You'd have to maintain the cron state outside the container so that it'd be persistent across container reboots, which defeats the "do it once in the container and not host".  Then you might have problems where the container wasn't running at appropriate times when the cron should hit.

**Comment by DavidPoliakoff** [comment]
Yeah, I'm with you on the cron concept being a dead one, `cron` is just how my brain says `do something regularly`, but it is really fragile

**Comment by mplegendre** [comment]
See https://github.com/LLNL/spotbe/tree/feature/onloadhook

I named the file SPOTHookOnFileLoad.sh.  It has to be in the same directory as the path you pass into the SPOT FE, and executable by the web server process.  Might be nice to eventually have it be able to modify the parameters/inputs/outputs flowing through the getData, but that would take a lot more design work.

I only unit tested this in spot.  I didn't do an end-to-end test.  Can you do that with your git use case and let me know how it goes?

**Comment by DavidPoliakoff** [comment]
Matt, will test and get back to you, have a noon meeting but first thing after

**Comment by DavidPoliakoff** [comment]
I must be doing something wrong, in a directory structure of

```
s1042027:exa3 dzpolia$ ls
2021_01_20_08:05:34.cali	2021_01_20_08:19:01.cali	2021_01_20_08:21:18.cali
2021_01_20_08:08:19.cali	2021_01_20_08:19:42.cali	SPOTHookOnFileLoad.sh
2021_01_20_08:10:12.cali	2021_01_20_08:20:34.cali
```

Even if I just comment out the contents of `SPOTHookOnFileLoad.sh` I can't see any of the profiles. Is the presence of that file somehow blocking the viz?

**Comment by mplegendre** [comment]
It shouldn't, and I didn't see that.  

Could you run spot.py  manually and report what it prints.  This would involve logging into the container and running something like:

% /opt/conda/bin/python3 /usr/gapps/spot/backend.py --config /usr/gapps/spot/backend_config.yaml getData $PATH_TO_YOUR_CALI_FILES '{}'

If this works it should spit out a bunch of JSON.  If it spits out an error message, what's that message?

**Comment by mplegendre** [comment]
Oh, you might need to run this as the spot user.  "su -u spot ....." first.

**Comment by DavidPoliakoff** [comment]
```
spot@293f75273efa:/usr/gapps/spot$ /opt/conda/bin/python3 /usr/gapps/spot/backend.py --config /usr/gapps/spot/backend_config.yaml getData /data/exa3
usage: backend.py getData [-h] [--lastRead LASTREAD] dataSetKey cachedRunCtimes
backend.py getData: error: the following arguments are required: cachedRunCtimes
```

Any thoughts?

**Comment by mplegendre** [comment]
That's a command line argument error, not related to the actual issue.  Add a pair of blank curly braces as a final parameter: '{}'

**Comment by DavidPoliakoff** [comment]
Ah, I think it's about how I'm hosting it, I'll need to open up a port on the container to let it do a git pull or something. I'll play with it, let you know what works

**Comment by DavidPoliakoff** [comment]
I hate to shock you, but it turned out that at the lab, a proxy server prevented something from working. I know, I know, be still our beating hearts. Snark aside, the functionality works :)

**Comment by DavidPoliakoff** [comment]
May have jumped the gun. I'll keep debugging, but it _looks_ like all the issues are proxy issues

**Comment by DavidPoliakoff** [comment]
Okay, the current status:

Just running that command in the bash prompt in my container works. But refreshing the dataset by in the SPOT web GUI doesn't.

So

```
/opt/conda/bin/python3 /usr/gapps/spot/backend.py --config /usr/gapps/spot/backend_config.yaml getData /data/exa3/ {}
```

That makes the git pull happen. But clicking on the refresh with a URL of

```
[spot]:8080/?sf=./exa3
```

Doesn't. Which is of course profoundly weird. Is the call to SPOTHookOnFileLoad.sh somehow gated behind some arguments to backend.py?

**Comment by DavidPoliakoff** [comment]
Another small thing: it looks like we don't run the script from within the directory, which makes things more difficult, It would be nice if we could switch to (for example) /data/exa3 before running a script there (I can hack around this by making the script "cd /data/exa3 && git pull --recurse-submodules origin master" but it's preferable to have it work independently of position)

**Comment by mplegendre** [comment]
Can do on that chdir.  It also passes the target directory as parameter $1.

I'm not sure why/how you'd have the python command work, but then not get data when running it from the web FE.  I'm in meetings the rest of the day, but I'll try to take a pass soonish and see if I can spot what could be happening.

**Comment by DavidPoliakoff** [comment]
Ah, didn't realize I got the directory as the first parameter, nice. Thanks for the quick turnaround/testing on this, I really appreciate it

**Comment by jrmadsen** [comment]
Just a thought here but having the database maintained it an entirely different container which the spot instance could make a request from over the local network might be a good idea. This would make it easier to configure when to update data, where all the data is located, how it responds to failures, etc.

**Comment by DavidPoliakoff** [comment]
I prefer it if things _can_ live in one container, or at least I want one command to hand somebody to run the thing

**Comment by jrmadsen** [comment]
I think it would also make it easier to make sure you don't end up with a bunch of junk in the spot container for stale data that should be discarded, e.g. when spot gets the data for a request, it just stores that data in a temp folder and is then free to delete all the data if it needs to.

**Comment by jrmadsen** [comment]
@DavidPoliakoff docker-compose is designed for this sort of thing.

**Comment by jrmadsen** [comment]
Actually, you will find that using docker-compose is actually a hell of a lot easier than using docker directly. E.g. `docker-compose up` can start a daemon, mount volumes in the right places, coordinate the network between multiple containers, etc. Basically, all those command-line args are put into a yml file

**Comment by jrmadsen** [comment]
Take a look at: https://github.com/NERSC/timemory/blob/develop/docker/docker-compose.yml

Here are the equivalents:

### docker-compose

```console
docker-compose build --pull timemory-cpu-dev
```

### docker

```console
docker build --pull -t nersc/timemory:dev-cpu -f Dockerfile.dev --build-arg COMPILER_SPEC="gcc@9.3.0" --build-arg VERSION=develop --build-arg PYTHON_VERSION="3.7.9" --build-arg GCC_VERSION=9 --build-arg CLANG_VERSION=11 cpu
```

**Comment by jrmadsen** [comment]
Here is more relevant example which I think I wrote for the old Rancher 1 version of cdash in Spin:

```yaml
version: '3.3'

services:
    cdash:
        container_name: cdash-docker
        # for interactive docker-compose
        stdin_open: true
        tty: true
        build: .
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - 8080:80
        networks:
            docker_server_network:
                ipv4_address: 172.24.10.2
        logging:
            driver: "json-file"
        restart: on-failure
        depends_on:
            - mysql
        secrets:
            - cdash_mysql_passwd
        volumes:
            - ./.config:/var/www/cdash/config/persistent
            - ./.log:/var/www/cdash/log
        environment:
            CDASH_DB_HOST: mysql
            CDASH_DB_NAME: cdash
            CDASH_DB_TYPE: mysql
            CDASH_DB_LOGIN: root
            CDASH_DB_PASS: ''
            CDASH_DB_CONNECTION_TYPE: host
            CDASH_ROOT_ADMIN_PASS: secret
            CDASH_USER_LIST: 'admin,user'
            CDASH_USER_admin_EMAIL: admin@docker.container
            CDASH_USER_admin_DISPOSITION: admin
            CDASH_USER_admin_FIRST_NAME: Admin
            CDASH_USER_admin_LAST_NAME: User
            CDASH_USER_admin_NEW_PASSWORD: adminsecret
            CDASH_USER_admin_INSTITUTION: docker
            CDASH_USER_user_EMAIL: user@docker.container
            CDASH_USER_user_DISPOSITION: user
            CDASH_USER_user_FIRST_NAME: Test
            CDASH_USER_user_LAST_NAME: User
            CDASH_USER_user_PASSWORD: usersecret
            CDASH_USER_user_INSTITUTION: docker
            DEBUG: 1

    mysql:
        container_name: mysql
        image: mysql/mysql-server:5.5
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: 'cdash'
            MYSQL_ROOT_HOST: '%'
        #
        secrets:
            - cdash_mysql_passwd
        volumes:
            # persistent local db files
            - ./.data/db:/var/lib/mysql
            - ./.data/db-files:/var/lib/mysql-files
            - ./.data/db-keyring:/var/lib/mysql-keyring
            - ./.data/db-upgrade:/var/lib/mysql-upgrade
        #
        networks:
            docker_server_network:
                ipv4_address: 172.24.10.3
        logging:
            driver: "json-file"


secrets:
    cdash_mysql_passwd:
        file: ./.secrets/cdash_mysql_passwd

networks:
    # network interface required to allow MySQL 'root' to be logged into remotely
    # from php:7-apache
    docker_server_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.24.10.0/24
```
